/**
 * The committed conformance report: one deterministic function from a {@link ConformanceRun} to the
 * markdown of `documentation/tx-conformance.md`.
 *
 * It lives beside the runner rather than inside the job script so that the job (which writes the
 * file) and the test (which re-derives it and compares) call the SAME renderer. A report generated
 * one way and checked another can agree on every number and still drift on everything else, which is
 * how a stale report survives the check that exists to catch it.
 *
 * @packageDocumentation
 */

import {
  APPLIED_TOLERANCES,
  DECLINE_REASONS,
  OPERATIONS_IN_SCOPE,
  SNAPSHOT_ROOT,
  SUITES_IN_SCOPE,
  SUPPORTED_REQUEST_PARAMETERS,
  type ConformanceRun,
} from "./tx-runner.js";

/** Where the committed report lives, relative to the repository root. */
export const REPORT_PATH = "documentation/tx-conformance.md";

/**
 * The suites the vendored snapshot deliberately omits, with the reason. Vendored content that would
 * trip a repository-wide check is narrowed, never exempted, so the omission is recorded here instead
 * of in an exclusion list inside the check.
 */
const OMISSIONS: readonly { readonly what: string; readonly reason: string }[] = [
  {
    what: "the registry's other 33 suites and its introduction, todo and not-done keys",
    reason:
      "six description strings in the upstream sct-ecl suite carry an em dash, which " +
      "`pnpm check:no-emdash` bans over every tracked file with no exclusion by path. The remedy " +
      "for vendored content that trips a repository check is to vendor less of it, never to add " +
      "an exclusion, an exemption or a skip. Keeping those suites' declarations without their " +
      "fixtures would also have named 1,715 absent files, which the runner treats as a hard " +
      "failure. No case in the three suites in scope was omitted, so this narrowing declines " +
      "nothing.",
  },
];

/** Render the committed report from a run. Deterministic: same run in, same bytes out. */
export function renderReport(run: ConformanceRun): string {
  const lines: string[] = [];
  const push = (s = ""): void => {
    lines.push(s);
  };

  push("# Terminology ecosystem conformance");
  push();
  push(
    "[GENERATED by `pnpm run conformance:tx --write`. Do not hand-edit: " +
      "`test/conformance/tx-conformance-report.test.ts` re-derives this file from a fresh run and " +
      "fails on any disagreement, so a hand-edit is a red, not a fix.]",
  );
  push();
  push(
    "How many of HL7's own terminology ecosystem test cases this engine answers identically. The " +
      "job runs in process, drives the package's public API, and never changes an engine answer: a " +
      "case that answers differently fails the job and is never recorded as a decline.",
  );
  push();

  push("## Snapshot");
  push();
  push(
    "| fact | value |\n|---|---|\n" +
      `| suite | HL7 FHIR terminology ecosystem test cases |\n` +
      `| snapshot version (upstream commit) | \`${run.snapshot}\` |\n` +
      `| vendored at | \`${SNAPSHOT_ROOT}\` |\n` +
      `| origin, pin and licence | \`vendor/tx-ecosystem/NOTICE.md\` |`,
  );
  push();
  push(
    "The suite publishes no version field, so the upstream commit is the version these counts were " +
      "produced against.",
  );
  push();

  push("## Selection");
  push();
  push(`- suites in scope: ${SUITES_IN_SCOPE.map((s) => `\`${s}\``).join(", ")}`);
  push(`- operations in scope: ${OPERATIONS_IN_SCOPE.map((o) => `\`${o}\``).join(", ")}`);
  push("- excluded: any case the registry marks with a server-specific `mode`");
  push();
  push("| suite | cases declared | cases selected |");
  push("|---|---|---|");
  for (const s of run.suites) {
    push(`| \`${s.name}\` | ${String(s.declared)} | ${String(s.selected)} |`);
  }
  push(`| **total** | **${String(run.declared)}** | **${String(run.selected)}** |`);
  push();
  push(
    "A case outside the selection is not counted as ran, passed or declined. The declared column is " +
      "here so that a narrowing of the selected set is visible beside the counts it would flatter.",
  );
  push();

  push("## Counts");
  push();
  push("| count | value |");
  push("|---|---|");
  push(`| ran | ${String(run.ran)} |`);
  push(`| passed | ${String(run.passed)} |`);
  push(`| declined | ${String(run.declined.length)} |`);
  push(`| answered differently | ${String(run.failed.length)} |`);
  push();
  push(
    "`ran` is every selected case: each one is passed, declined or answered differently, and the " +
      "three add up to it by construction.",
  );
  push();

  push("## What is compared");
  push();
  push(
    "The recorded responses declare their own tolerance and the runner honours it: " +
      "`$optional-properties$` (elements that need not be present), `$optional$` (one element that " +
      "need not be present), the `$id$` / `$uuid$` / `$instant$` placeholders for values that " +
      "legitimately vary per run, and the `response:flat` variant a fixture supplies for a server " +
      "that does not build a hierarchical expansion.",
  );
  push();
  push(
    "Beyond that vocabulary the runner applies the tolerances below. Every one exists because the " +
      "suite records a server's HTTP response while this package is a library whose answer is " +
      "narrower by construction. They are named here because a tolerance nobody can see is " +
      "indistinguishable from a pass that was not earned.",
  );
  push();
  for (const t of APPLIED_TOLERANCES) {
    push(`- **${t.id}**: ${t.text}`);
  }
  push();

  push("## Declines");
  push();
  push("The closed set of reasons a case may be declined for:");
  push();
  for (const r of DECLINE_REASONS) {
    push(`- \`${r}\``);
  }
  push();
  push(
    "An `engine-refusal:` reason carries the engine's own typed code. Anything the engine does that " +
      "is not one of those codes is a failure, not a decline. The request parameters the public " +
      `surface answers are ${SUPPORTED_REQUEST_PARAMETERS.map((p) => `\`${p}\``).join(", ")}; a ` +
      "case naming any other parameter is declined rather than answered from a guess.",
  );
  push();
  if (run.declined.length === 0) {
    push("No case was declined.");
  } else {
    push("| suite | case | reason | what triggered it |");
    push("|---|---|---|---|");
    for (const d of run.declined) {
      push(`| \`${d.suite}\` | \`${d.name}\` | \`${d.reason}\` | ${d.detail} |`);
    }
  }
  push();

  push("## Answered differently");
  push();
  if (run.failed.length === 0) {
    push("None. Every case that was compared answered what the fixture recorded.");
  } else {
    push("| suite | case | diverges at | recorded | answered |");
    push("|---|---|---|---|---|");
    for (const t of run.failed) {
      push(`| \`${t.suite}\` | \`${t.name}\` | ${t.point} | ${t.recorded} | ${t.answered} |`);
    }
  }
  push();

  push("## Omitted from the vendored snapshot");
  push();
  for (const o of OMISSIONS) {
    push(`- **${o.what}**: ${o.reason}`);
  }
  push();

  return `${lines.join("\n").replace(/\n+$/, "")}\n`;
}
