#!/usr/bin/env tsx
/**
 * Generator: embed the vendored, **verbatim** `ucum-essence.xml` into a TypeScript module as a
 * string constant (`src/ucum/essence-data.generated.ts`).
 *
 * The UCUM License (<https://ucum.org/license>) forbids modifying the Work's content or creating
 * Derivative Works of the UCUM table, but permits verbatim reproduction/distribution (with notice)
 * and the development of software that interacts with UCUM. So we ship the table **byte-for-byte**
 * (this script only wraps it as a JS string literal; the UCUM content is untouched), and the
 * engine transforms it into a lookup table lazily at runtime (`src/ucum/essence.ts`). See
 * `vendor/ucum/NOTICE.md`.
 *
 * Zero runtime deps: the generated module is plain JS a bundler can inline, so the engine reads no
 * file at runtime. Regenerate with `pnpm gen:ucum` whenever the vendored essence file is updated;
 * `test/ucum/essence-data.generated.test.ts` guards against drift.
 *
 * Pure Node, dev-only (never shipped). Not a runtime dependency.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const essencePath = join(repoRoot, "vendor", "ucum", "ucum-essence.xml");
const outPath = join(repoRoot, "src", "ucum", "essence-data.generated.ts");

const xml = readFileSync(essencePath, "utf8");

// The vendored essence is pure ASCII with no backticks, backslashes, or `${` sequences (verified in
// CI by the drift test), so a template literal reproduces it byte-for-byte. Guard anyway: if a
// future essence revision introduces one of these, fail loudly rather than emit a corrupted copy.
if (/[`\\]|\$\{/.test(xml)) {
  throw new Error(
    "vendored ucum-essence.xml contains a backtick, backslash, or ${: the verbatim template-literal " +
      "embedding is no longer byte-safe; update the generator's escaping before regenerating.",
  );
}

const banner = `/**
 * The **verbatim, unmodified** UCUM unit table (\`ucum-essence.xml\`), embedded as a string.
 *
 * GENERATED by \`scripts/generate-ucum-essence-data.ts\` from \`vendor/ucum/ucum-essence.xml\`:
 * **do not edit by hand**. The content is UCUM's, reproduced byte-for-byte; only the string wrapper
 * is added. Regenerate with \`pnpm gen:ucum\`.
 *
 * The Unified Code for Units of Measure (UCUM) is copyright ©1999–2024, Regenstrief Institute, Inc.
 * All rights reserved. Reproduced under the UCUM Copyright Notice and License
 * (https://ucum.org/license); this copy is unmodified. Provided "as is" without warranty of any
 * kind. See \`vendor/ucum/NOTICE.md\`.
 *
 * @packageDocumentation
 */

// prettier-ignore
/**
 * The verbatim UCUM \`ucum-essence.xml\` v2.2 (revision-date 2024-06-17). Parsed lazily by
 * {@link ../ucum/essence.loadUcumEssence} into the engine's in-memory unit table.
 */
export const UCUM_ESSENCE_XML: string =`;

const body = `${banner} \`${xml}\`;\n`;
writeFileSync(outPath, body, "utf8");
process.stdout.write(`wrote ${outPath} (${String(xml.length)} chars embedded verbatim)\n`);
